# Generated by Django 5.0.14 on 2026-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_attendance_document_internshiprecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('RESUME', 'Resume'), ('ACADEMIC_RECORD', 'Academic Record'), ('OTHER_REQUIREMENT', 'Other Requirement')], default='OTHER_REQUIREMENT', max_length=30),
        ),
    ]
